export const projects = [
  {
    title: 'Instagram-Clone',
    description: "It is a MERN Stack project, which includes the features like  authentication, likes,comments,creating a  post,  follow and unfollow users like these all functionalities included adn cloned the instagram.",
    image: '/images/instagram.jpg',
    tags: ['Express','Mongo','React','Nodejs'],
    source: 'https://github.com/Ishwarya-Kanagaraman/instagram-clone',
    visit: 'https://instag-clone24.herokuapp.com/',
    id: 4,
  },
  {
    title: 'E-commerce Application',
    description: "It is a MERN Stack project, which includes the authentication, shopping, payment methods and have admin controls, with some more extra features.",
    image: '/images/e-commerce.jpg',
    tags: ['Express','Mongo','React','Nodejs'],
    source: 'https://github.com/Ishwarya-Kanagaraman/ecommerce',
    visit: 'https://ecommerce-24.netlify.app/',
    id: 4,
  },
  {
    title: 'Admin Dashboard',
    description: "Using React,Bootstrap,HTML and CSS I learnt how to an Entire Admin Dashboard  - from start to finish. The App is called Memories and it is a simple  app that allows users to do CRUD operation in their Users.",
      image: '/images/adminDashboard.png',
      tags: ['Bootstrap', 'HTML', 'CSS', 'React'],
    source: 'https://github.com/Ishwarya-Kanagaraman/dashboard-crud1',
    visit: '	https://60faaba6bee07500b7ebc5db--dashboard-with-crud.netlify.app/',
    id: 0,
  },
  {
    title: 'Assigning Mentors',
    description: "A simple software training center Website Using Mongo,Express,React and Nodejs where we can add the students,Assign Mentors to students, and change mentor to students. ",
      image: '/images/mentorAssign.jpg',
      tags: [ 'Express','Mongo','React','Nodejs'],
    source: 'https://github.com/Ishwarya-Kanagaraman/student-mentor-assign-client',
    visit: 'https://student-mentor-assign-client.netlify.app/',
    id: 2,
  },
  {
    title: 'Shopping-Cart',
    description:"Here In this project a simple E-commerce shop app is built. We can add or remove the cart items  and able to see the Total amount. We can also increase/decrease the count of product in the cart. ",
    image: '/images/shoppingcart.jpg',
    tags: ['React', 'JavaScript','HTML','CSS'],
    source: 'https://github.com/Ishwarya-Kanagaraman/Shopping-cart',
    visit: 'https://60d4af61f6d53435f2de6454--kind-poincare-75d249.netlify.app/',
    id: 1,
  },
  {
    title: 'Whatsapp Clone',
    description: "It is a mern stack project where Pusher is used for real time chat and it replicated the UI of whatsapp",
    image: '/images/whatsapp_app.webp',
    tags: ['Express','Mongo','React','Nodejs'],
    source: 'https://github.com/Ishwarya-Kanagaraman/whatsapp-clone-backend',
    visit: 'https://whatsapp-clone-frotend.netlify.app/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2014, text: 'Completed SSLC with 98%', },
  { year: 2016, text: 'Completed HSC with 96%', },
  { year: '2020 (Sep)', text: 'Completed BE(ECE) with CGPA 7.1', },
  { year: '2020 (Nov)', text: 'Started My career in Web development', },
  { year: 2021, text: 'Started developing web application', },
];